parser: "babel-eslint"
env:
  browser: true
  es6: true
extends:
  - "airbnb"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - import
  - jsx-a11y
rules:
  react/prop-types: 0
  react/jsx-filename-extension:
    - 1
    - extensions:
        - ".js"
        - ".jsx"
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
